apiVersion: argoproj.io/v1alpha
kind: Application
metadata:
  name: app
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/NicolasMetais/IOT-argoCD.git
    targetRevision: HEAD
    path: .
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    
