Vagrant.configure("2") do |config|
  config.vm.box = "debian/trixie"

  #SERVER
  config.vm.define "nmetaisS" do |server|
    server.vm.hostname = "nmetaisS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.name = "nmetaisS"
      vb.memory = 2048
      vb.cpus = 2
    end
      server.vm.provision "shell", path: "scripts/server.sh"
  end
end