
Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  #SERVER
  config.vm.define "nmetaisS" do |server|
    server.vm.hostname = "nmetaisS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.name = "nmetaisS"
      vb.memory = 2048
      vb.cpus = 2
    end

    server.vm.provision "shell", path: "scripts/server.sh"
  end

  #WORKER
  config.vm.define "nmetaisSW" do |worker|
    worker.vm.hostname = "nmetaisSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |vb|
      vb.name = "nmetaisSW"
      vb.memory = 512
      vb.cpus = 1
    end
    worker.vm.provision "shell", path: "scripts/worker.sh"
  end
end
